import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-container": "#562000",
        "on-primary": "#00363d",
        "inverse-primary": "#006875",
        "error-container": "#93000a",
        "on-background": "#e1e1ef",
        "surface-bright": "#373943",
        "surface-dim": "#11131c",
        "surface-container": "#1d1f29",
        "surface-container-high": "#282933",
        outline: "#849396",
        tertiary: "#eaedef",
        background: "#11131c",
        "on-primary-container": "#00626e",
        "tertiary-container": "#ced1d3",
        "inverse-surface": "#e1e1ef",
        "on-tertiary": "#2d3133",
        "on-secondary-fixed": "#341100",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-secondary-fixed-variant": "#7a3000",
        "on-secondary": "#562000",
        "tertiary-fixed": "#e0e3e5",
        "primary-fixed-dim": "#00daf3",
        "inverse-on-surface": "#2e303a",
        error: "#ffb4ab",
        "primary-fixed": "#9cf0ff",
        primary: "#c3f5ff",
        "on-primary-fixed": "#001f24",
        "on-tertiary-fixed": "#181c1e",
        "on-tertiary-container": "#565a5c",
        "on-surface": "#e1e1ef",
        "surface-tint": "#00daf3",
        "secondary-fixed": "#ffdbcb",
        "primary-container": "#00e5ff",
        "on-surface-variant": "#bac9cc",
        "surface-container-lowest": "#0c0e17",
        secondary: "#ffb692",
        "secondary-container": "#fd6c00",
        "on-primary-fixed-variant": "#004f58",
        "surface-variant": "#32343e",
        "outline-variant": "#3b494c",
        "on-tertiary-fixed-variant": "#434749",
        surface: "#11131c",
        "surface-container-low": "#191b24",
        "secondary-fixed-dim": "#ffb692",
        "on-error": "#690005",
        "surface-container-highest": "#32343e",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
